# -*- coding: utf-8 -*-
"""Googloe_Finance.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NxkBEdxInj3N1r-AuNCl-Iu6mqaybYJ_
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pandas_datareader.data as web

!pip install yfinance --upgrade --no-cache-dir
import yfinance as yf
yf.pdr_override()

#get data
ibov = web.get_data_yahoo('^BVSP')

ibov.head()

ibov.tail()

ibov_fatiado =ibov[(ibov.index.year >= 2008) & (ibov.index.year <= 2015)]
ibov_fatiado["Close"].plot(figsize=(22,8), label="IBOV")
ibov_fatiado["Close"].rolling(21).mean().plot(label="MM21")
ibov_fatiado["Close"].rolling(200).mean().plot(label="MM200")
plt.legend()

ibov_fatiado = ibov[ibov.index.month == 12]
ibov_fatiado.tail(50)

vale = web.get_data_yahoo('VALE3.SA',start='2010-05-03',end='2013-03-01')

vale.head()

vale =ibov[(ibov.index.year >= 2008) & (ibov.index.year <= 2015)]
vale["Close"].plot(figsize=(22,8), label="IBOV")
vale["Close"].rolling(21).mean().plot(label="MM21")
vale["Close"].rolling(200).mean().plot(label="MM200")
plt.legend()